services:
  # Relational Database
  db:
    container_name: database
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.postgres
    ports:
      - "5432:5432"

  # PgAdmin4
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    command: ["pgadmin4", "-f"]
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      db:
        condition: service_started
    ports:
      - "5050:80"

  # Django Application
  api:
    container_name: web
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - static:/src/app/static
      - static:/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_started
    restart: on-failure

  # React Application
  react:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      api:
        condition: service_started
    restart: on-failure

volumes:
  postgres_data:
  static:
  media:
  pgadmin_data:
