name: Deploy nginx

on:
  push:
    paths:
      - "prueba-3/index.html"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          cd prueba-3
          docker build -t my-nginx:latest .
      - name: Deploy Docker image
        run: |
          docker run -d -p 8080:80 my-nginx:latest
      - name: Check if the container is running
        run: |
          docker ps
      - name: Check updated file content
        run: |
          curl -s http://localhost:8080 | grep -oP '(?<=<h1>).*(?=</h1>)'
      - name: Stop the container
        run: |
          docker stop $(docker ps -q)
