name: Deploy nginx

on:
  push:
    paths:
      - "prueba-3/index.html"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          cd prueba-3
          docker build -t my-nginx:latest .
      - name: Deploy Docker image
        run: |
          docker run -d -p 8080:80 my-nginx:latest
